services:
  frontend:
    build:
      context: ./FRONTEND
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "4300:80"
    restart: unless-stopped

  backend:
    build:
      context: ./BACKEND
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      CADENA_SQL: "Server=upe2025g3.duckdns.org,1433;Database=UPECLINICA;User Id=SA;Password=Upe2025G3$;TrustServerCertificate=True;Encrypt=False;"
      Storage__RootPath: "/data/upeclinica/files"
    ports:
      - "5259:5259"
    volumes:
      - upe_files:/data/upeclinica/files
    restart: unless-stopped

volumes:
  upe_files:
